### ISSUE TITLE
Value {'signal_values': ['no_signal', 'on_off']} of type <class 'dict'> is invalid for Light.signaling, expected value of type typing.Optional[aiohue.v2.models.feature.SignalingFeature]

### ISSUE THREAD

**Issue by codyc1515** [home-assistant-libs/aiohue#187]
Since a few weeks I have been getting the following error messages:

```
Value {'signal_values': ['no_signal', 'on_off']} of type <class 'dict'> is invalid for Light.signaling, expected value of type typing.Optional[aiohue.v2.models.feature.SignalingFeature]
Value {'signal_values': []} of type <class 'dict'> is invalid for Light.signaling, expected value of type typing.Optional[aiohue.v2.models.feature.SignalingFeature]
```

They appear to be related to this line: https://github.com/home-assistant-libs/aiohue/blob/8662c48498a1660149d5a3eac56232c508817a7d/aiohue/v2/models/feature.py#L502

**Comment by marcelveldt** [comment]
Nah, the Hue API docs are not in line with what they're actually sending so we log when that happens (instead of failing). That way we can detect that either the API updated or the docs are wrong ;-)

I've seen a few reports of this now so I will adjust the datamodels to the reports and at the same time I'll adjust the loglevel to debug for this as the API is pretty stable now and i don't expect a lot of changes anymore.
