### ISSUE TITLE
v2.3.1 (and up?) not connecting to hue v1 bridge

### ISSUE THREAD

**Issue by kiss81** [home-assistant-libs/aiohue#57]
currently home assistant is using v2.3.1 of the aiohue library. When it used v2.1.0 all was working well with my v1 hue bridge. After the aiohue library is updated to v2.3.1 it's not connection anymore. It might have to do because the v1 bridge uses non https for the communication, but I am not sure of this. I manually rolled back to v2.1.0 for now. I tried 2.5.0 as well, but it doesn't connect either...

**Comment by balloob** [comment]
Do you have a log / stack trace with errors? 

How do you use aiohue?

**Comment by atika** [comment]
I tried to manually add my virtual lights configured in Node-Red, which should use the v1 API, to Home Assistant. He tries to get a missing key `bridgeid` from the root JSON response with a 12 characters length (`discovery.py`).  Verified with my real bridge and it returns this `bridgeid` key. Verified aiohue v2.1.0, the `bridgeid` came from the `config.bridgeid`.

```
File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 71, in _get_bridge
    bridge = await discover_bridge(
  File "/usr/local/lib/python3.9/site-packages/aiohue/discovery.py", line 35, in discover_bridge
    bridge_id = await is_hue_bridge(host, websession)
  File "/usr/local/lib/python3.9/site-packages/aiohue/discovery.py", line 82, in is_hue_bridge
    return normalize_bridge_id(data["bridgeid"])
KeyError: 'bridgeid'
```

**Comment by balloob** [comment]
So that's a bug with Node Red not following the spec.

**Comment by atika** [comment]
Maybe I wrong but I don't see in the v1 of the specs a `bridgeid` returned by the api endpoint `/api/config`. I verified on the developer website, and the JSON returned by Node Red is almost the same: [https://developers.meethue.com/develop/hue-api/7-configuration-api/](https://developers.meethue.com/develop/hue-api/7-configuration-api/) (7.5.3 Sample Response). 

In the mentioned v2.1.0, the `bridge id` came from the `id` in the response of the method  `discover_nupnp()` and the config was created from the config object. I think the bridge id came from the mac address on v1.

https://github.com/home-assistant-libs/aiohue/blob/2654b8bc00a87f403cb8b5f8c79684ff89ee0937/aiohue/discovery.py#L4-L13

This means that the method `is_hue_bridge(host: str, websession: ClientSession | None = None)` in [discovery.py](https://github.com/home-assistant-libs/aiohue/blob/6e8654af4dd1a61998f467e14fbb6afab576c7fb/aiohue/discovery.py#L67) should only works with the v2 of the api and crash with v1 because the key `bridgeid` does not exists.

https://github.com/home-assistant-libs/aiohue/blob/6e8654af4dd1a61998f467e14fbb6afab576c7fb/aiohue/discovery.py#L67-L85

**Comment by marcelveldt** [comment]
bridgeid is in fact part of the config object.
https://developers.meethue.com/develop/hue-api/7-configuration-api/#get-configuration

Can you explain what is the issue ?

**Comment by atika** [comment]
Finally for me there is no issue, I understand where the problem came from. @kiss81 is your problem related to a physical Hue bridge v1 ?

I explain...

The module get the config from the endpoint: `/api/config` and should returns a response like this:

```json
{
    "name": "Philips hue",
    "apiversion": "1.10.0",
    "swversion": "01028090",
    "mac": "00:17:88:20:01:0a",
    "bridgeid": "001788FFFE20010A",
    "replacesbridgeid": null,
    "factorynew": false,
    "modelid": "BSB001"
}
```

And not (like the Node Red module do):

```json
{
   "lights": {},
   "groups": {},
   "config": {
       [...]
        "bridgeid": "001788FFFE20010A",
        "modelid": "BSB001"
   }
}
```

who is the __full state__ from the endpoint `/api/<username>`

Sorry for the waste of time. After adding manually the missing keys Home Assistant added the virtual hub.

I just have a question, it is wanted  that there is no test on the existence of the key `bridgeid` and the log returns a full error traceback? On the one hand without this I will not catch where the problem was...

**Comment by marcelveldt** [comment]
I think we can leave this one closed. The purpose of the aiohue library is connecting to REAL Hue bridges (V1 or V2). We will not add workarounds for virtual bridges. The virtual bridge should instead confirm to the api specs if it want to stay/be compliant.
